name: somasawa_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.5.2
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.5
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.1
  go_router: ^13.0.0
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.0
  material_symbols_icons: ^4.2713.0
  path: ^1.8.3
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  uuid: ^4.2.2
  table_calendar: ^3.0.9
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  amplify_lints: ^3.0.0
  build_runner: ^2.4.7
  custom_lint:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.3
  riverpod_lint: ^2.1.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/no_class_curriculum.svg
  - assets/images/completed_setup.svg
  - assets/images/no_weekly_objective.svg
  - assets/images/image-not-found-icon.svg
  - assets/images/image_icon_filled.svg
  - assets/images/image_icon_left.svg
  - assets/images/img_icon_left_indigo_900.svg
  - assets/images/img_nav_agenda.svg
  - assets/images/img_nav_curriculum.svg
  - assets/images/img_nav_home.svg
  - assets/images/img_nav_icon_unfilled_indigo_900_48x48.svg
  - assets/images/img_nav_student.svg
  - assets/images/img_new_icon.svg
  - assets/images/img_new_icon_unfilled.svg
  - assets/images/img_new_icon_unfilled_indigo_600.svg
  - assets/images/img_new_icon_unfilled_indigo_900.svg
  - assets/images/img_new_icon_unfilled_red_700.svg
  - assets/images/img_vector.svg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
